[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test/foundry"
cache_path = "cache_foundry"

# Compiler settings
solc_version = "0.8.17"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing settings
verbosity = 2
fuzz_runs = 1000
fuzz_max_test_rejects = 65536

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = []

# Remappings for imports
remappings = [
    "@chainlink/=lib/chainlink/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/ds-test/src/"
]

# Profile for CI/CD
[profile.ci]
fuzz_runs = 10000
verbosity = 4

# Profile for gas optimization
[profile.gas-optimize]
optimizer = true
optimizer_runs = 10000
via_ir = true